console.log("page data loaded");
var pageData = [
  {
    countryName: "China",
    countrySlogan: "\"We're taking over the world\"",
    welcomeBackground: "http://vignette2.wikia.nocookie.net/steamtradingcards/images/1/11/Guilty_Gear_Isuka_Background_China.jpg/revision/latest?cb=20140520060849",
    themeColor: "#E53935",
    articles: [
      {
        title: "China Censor’s Everything!!! Right?",
        author: "Dixon Layton",
        content: [
          "Because we live in a western country that enjoys many freedoms not universal to the world, we tend to think things about other countries based on some innate comparison to the experiences we have. This is neither unexpected nor bad, but it can get us into traps when thinking about countries that are fundamentally different than we are. China’s free speech and internet censorship policies are one of the easiest places to get caught up in western frames of mind, because the mindset in China regarding these topics seems irrational and crazy to us, despite it being perfectly normal in China.",
          "The most obvious area where we expect there to be issues is with free speech, because we always assume that in a country where that doesn’t exist, absolutely everyone who does will get taken in. That is simply not the case in China, where certain individuals--like the artist Ai Weiwei--have been actively trying to counter the government’s rhetoric. Of course, it is true that some of the most outspoken and revolutionary activists have been arrested, but on the whole that’s not the case, because the Chinese government has been very smart about this. They recognize that if they were to arrest their opponents in the most public way, then it would lead to problems, so in effect they just ignore them, and no one has a big enough following to make any revolution happen.",
          "Furthermore, the internet policies that China has put in place also seem tyrannical to those of us outside China, but within it, their view is very different. The young in China have never known a time when the internet wasn’t censored, and so they essentially don’t know there is something to miss. Because of the lack of western media and influence on the Chinese internet, and the replacement of the sites we know and love (Google, Facebook, Twitter, Amazon) with equivalent sites in China (Baidu, renren.com, Weibo, Taobao), they have no real need to look for things outside of China’s borders. However, they could if they tried, and that is another misconception about China’s internet policy: that they try their hardest to make it impossible to see banned sites. In fact, it’s relatively easy to get on a foreign site in China, if you know what you’re doing. I don’t, so I can’t really explain it, but the Chinese government itself doesn’t particularly care if individuals gain access to the outside world, they can’t exactly stop them, and if a Chinese person travels and then accesses the internet, they can’t do anything. They live in a big enough country that individuals with banned information can’t do much, so they let it slide almost every time. They focus on closing the biggest holes, and then let their independent volunteer army of searchers, the “50 cent party,” find the rest. These are essentially regular citizens who find instances of infringements on the web, and alert overseers who made them. They are anonymous, and a rather Orwellian group, but are independent. They only report to the government, and in reality they don’t find all that much, because the majority of China self-censors their web content, because they have no reason to act out; as I said earlier, they grew up under the censorship, and don’t truly know the difference.",
          "Essentially, to understand the roots of free speech and internet censorship in China, we have to let go of the things we consider universal and given, because they don’t hold true all across the world. The chinese are not in the US and have a very different culture to what we have, and so without understanding that fact, their relationship to those two areas will not make sense. All of the evidence above draws from those ideas, that China is very very different from us, and that’s why they accept the censorship and restrictions on free speech."
        ]
      },
      {
        title: "WHY CHINA IS NOT TAKING OVER THE WORLD. CHINA IS KILLING US/CHINA IS RICHER THAN US",
        author: "Kevin Qiwei",
        content: [
          "China is not taking over the world and isn’t going to defeat the US or something - China currently has too much of its interests tied intimately together with its economics and so much of it is integrated into a global, modern-day economy that it risks imploding onto itself if it tries to do anything to upset the global status quo by too much. Most of China’s power is in its soft power in form of economy, not as much in military hard power. Despite frequent claims of Chinese military getting more and more powerful (which have a grain of truth to them), the Chinese military is still decidedly less powerful than that of the US. China is surrounded by countries aligned with the US (Japan, South Korea, Philippines for example) and is currently in the middle of a very difficult economic transition, so it’s got a lot of domestic issues to take care first. The Economist claimed that “It is a question of when, not if, real trouble will hit in China” with regards to a debt bust that it thinks China is going to have soon, showing that mainstream media also recognize the difficulties China is having with its economy (for further reference look at China’s stock market). There are many issues with the Chinese economy, and it may take only one of them to implode the Chinese market and send it into turmoil. Furthermore, the most recent incarnation of China’s government is also relatively young and untested, and it remains to be seen whether it can whether all kinds of challenges, such as world wars and major economic downturns and come out better than before.",
          "As for China getting richer than the US and all such hype, as of 2014 the US is 22.3% of world economy by GDP, while China is only 13.4%. It would take China a very long time, if ever, to catch up with and exceed the economic prowess of an established superpower. Minus all kinds of structural problems, such as increasingly inefficient state-run giants (the world’s top 4 biggest banks by asset are all state-run Chinese banks, and China’s “3 oil buckets” take up 2nd to 4th in the world by revenue), centralized command economy blocking market-orientated reforms and the debt/high-risk lending issues all across China, China still has a long way to go to surpass the US."
        ]
      },
      {
        title: "COMMUNISM/CAPITALISM IN CHINA",
        author: "Lizzy Wu",
        content: [
          "It seems contradictory that Mao’s communist policies have been replaced with Deng Xiaoping’s more capitalist ones. While the government is communist, the economy is capitalist, yet the two competing ideologies have historically been so incompatible that a Cold War was born. From our western perspective, we find it difficult to fully understand Chinese economics because we are too focused on trying to slap either a communist or capitalist label on China as a whole. How does China reconcile the two ideologies and why?",
          "Deng Xiaoping looked at the historical success rate of command economies (economies that are controlled completely by the government), and realized that it was ineffectual, inefficient, and costly because no leader or group of leaders can be completely omniscient to know all the market trends from cabbage to shoes. This leads to shortages and surpluses which also leads to social unrest. Capitalist economies on the other hand are the complete opposite (although still very flawed), and dictated by the invisible hand of supply and demand. Because of Mao’s misguided allocation of human resources (telling millions of people to stop work and smelt useless steel in backyards or replacing doctors with high school students), an estimated 15 to 45 million deaths ensued in the Great Leap Forward. This is an example of ineffectual economic policy. In order for China to be a dominant world power, a centralized economy was not the answer, but neither was the overturning of a communist government that so effectively inspires nationalism. Deng Xiaoping came into government with a fresh perspective that contrasted with Mao’s diehard communism. “We mustn't fear to adopt the advanced management methods applied in capitalist countries... The very essence of socialism is the liberation and development of the productive systems... Socialism and market economy are not incompatible”"
        ]
      }
    ]
  }
]
